baseURL: 'https://dalamkotak.onrender.com'
languageCode: en-us
title: DalamKotak
enableEmoji: true
disqusShortname: didalamkotak-netlify-app
paginate: 200
enableRobotsTXT: true
hasCJKLanguage: true
summaryLength: 2
taxonomies:
  kategori: kategori
  topik: topik
# disableKinds:
#   - categories
#   - tags
markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute:
        block: false
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: false
      unsafe: false
      xhtml: false
Author:
  name: Oktoala
  bio: Ordinary Student
  avatar: img/codoala.png
Params:
  subtitle: ''
  copyright: DalamKotak | Dibuat menggunakan Hugo
  opengraph: true
  readmore: false
  authorbox: true
  toc: true
  pager: true
  post_meta:
    - author
    - date
    - translations
  sidebar:
    home: false
    list: false
    single: true
    widget:
      - categories
  logo:
    image: img/logoBaru.png
    title: Dalam Kotak
  style:
    vars:
      highlightColor: '#fff400'
      fontFamilyPrimary: "'Inter','Merriweather', Quicksand, Roboto, Helvetica, Arial, sans-serif"
      fontFamilySecondary: "Domine, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace"
  widgets:
    recent_num: 5
    tags_counter: true
    social:
      twitter: iansyah
      instagram: yogatra29
      telegram: yogatra29
      github: oktoala
      email: okta.yoga.syah@egmail.com
